name: Deploy to Fly.io

on:
  push:
    branches:
      - main
    paths:
      - "client/**"
      - "node-server/**"
      - "springboot-server/**"
      - "Dockerfile"
      - "fly.prod.toml"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy app
    runs-on: ubuntu-latest
    
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      
    concurrency:
      group: deploy-group
      cancel-in-progress: false

    steps:

      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      # Login Docker to Fly registry
      - name: Login to Fly registry
        run: flyctl auth docker

      # Build image tagged for YOUR Fly app
      - name: Build Docker image
        run: |
          docker build \
            --build-arg VITE_GEOCODE_URL=${{ secrets.VITE_GEOCODE_URL }} \
            --build-arg VITE_MAP_API_KEY=${{ secrets.VITE_MAP_API_KEY }} \
            --build-arg VITE_ENV=prod \
            -t registry.fly.io/healthcare-assistance:latest .

      # Push image to Fly
      - name: Push image
        run: docker push registry.fly.io/healthcare-assistance:latest

      # Deploy WITHOUT building
      - name: Deploy to Fly
        run: flyctl deploy -c fly.prod.toml --image registry.fly.io/healthcare-assistance:latest
