name: healthcare-assistance
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            CI: true
            MONGO_URL: mongodb://localhost/healthcare-assistance

        strategy:
            matrix:
                node-version: [20.x]
                mongodb-version: ["7.0"]

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node version ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            
            - name: Start MongoDB from GitHub actions
              uses: supercharge/mongodb-github-action@1.11.0
              with:
                mongodb-version: ${{ matrix.mongodb-version }}
            
            - name: Install Serverless backend dependencies
              run: |
                cd api
                npm install
            
            - name: Install Node Server backend dependencies
              run: |
                cd node-server
                npm install

            - name: Build Frontend
              run: |
                cd client
                npm install
                npm run build:deploy